#!/bin/bash
# homebrewupdate


export PATH=/usr/local/bin:$PATH
notifier=terminal-notifier

# Give the network a chance to connect
sleep 10

brew update > /dev/null 2>&1
outdated=`brew outdated | sort | tr '\n' ' '`

if [ ! -z "$outdated" ]; then
	reply=`$notifier -group my.mac.homebrewnotify -title "Homebrew Outdated" -message "$outdated" -closeLabel Leave -actions Upgrade -activate com.apple.Terminal`

  if [ "$reply" == "Upgrade" ]; then
    upgrade=`brew upgrade 2>&1`
#    echo $(hostname) : "$outdated" : "$upgrade" > /tmp/upgrade 2>&1
    if [ ! -z $1 ]; then
      echo $(hostname) : "$outdated" : "$upgrade" | mail -s "Homebrew Upgrade" $1
    fi
  elif [ ! -z $1 ]; then
    echo $(hostname) : "$outdated" | mail -s "Homebrew Outdated" $1
  fi
fi
